name: flutter_downloader_example
description: Demonstrates how to use the flutter_downloader plugin.
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"

dependencies:
  android_path_provider: ^0.3.0
  device_info: ^2.0.3
  flutter:
    sdk: flutter
  flutter_downloader:
    path: ../
  path_provider: ^2.0.11
  permission_handler: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^2.0.0+1

flutter:
  uses-material-design: true
