name: flutter_downloader
description: Powerful plugin making it easy to download files.
version: 1.10.4
repository: https://github.com/fluttercommunity/flutter_downloader
issue_tracker: https://github.com/fluttercommunity/flutter_downloader/issues
maintainer: Bartek Pacia (@bartekpacia)

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutterdownloader
        pluginClass: FlutterDownloaderPlugin
      ios:
        pluginClass: FlutterDownloaderPlugin

environment:
  sdk: '>=2.17.0 <3.0.0'
  flutter: '>=3.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^2.0.0+1
