name: flutter_downloader
description: Powerful plugin making it easy to download files.
version: 1.12.0
repository: https://github.com/fluttercommunity/flutter_downloader
issue_tracker: https://github.com/fluttercommunity/flutter_downloader/issues
maintainer: Salma (@salmaahhmed)

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutterdownloader
        pluginClass: FlutterDownloaderPlugin
      ios:
        pluginClass: FlutterDownloaderPlugin

environment:
  sdk: ">=3.6.0 <4.0.0"
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  leancode_lint: ^15.0.0
