name: flutter_downloader
description: A plugin for creating and managing download tasks. Supports iOS and Android.
version: 1.7.3
homepage: https://github.com/fluttercommunity/flutter_downloader
maintainer: Hung Duy Ha (@hnvn)

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutterdownloader
        pluginClass: FlutterDownloaderPlugin
      ios:
        pluginClass: FlutterDownloaderPlugin

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.20.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
